 #
 # Copyright (c) 2017 Nourreddine HOUARI (houarinourredine@gmail.com)
 # 
 # Permission is hereby granted, free of charge, to any person obtaining
 # a copy of this software and associated documentation files (the
 # "Software"), to deal in the Software without restriction, including
 # without limitation the rights to use, copy, modify, merge, publish,
 # distribute, sublicense, and/or sell copies of the Software, and to
 # permit persons to whom the Software is furnished to do so, subject to
 # the following conditions:
 # 
 # The above copyright notice and this permission notice shall be
 # included in all copies or substantial portions of the Software.
 # 
 # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 # EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 # MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 # NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 # LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 # OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 # WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 #
version: "2"

services:

  # Track server container
  trackrepository:
    image: hin/trackrepository
    environment:
      KAFKA_AUTO_RESET: earliest
      KAFKA_GROUPID: trackGroup
      KAFKA_TRACK_TOPIC: trackTopic
      KAFKA_SERVER_HOST: kafka
      KAFKA_SERVER_PORT: 9092
      ADSB_SERVER_HOST: pub-vrs.adsbexchange.com
      ADSB_SERVER_PORT: 32005
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: trackrepository
      DB_PASSWORD: trackrepository
    depends_on: 
      - kafka
      - db  

 # Track server database container
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_USER: trackrepository
      POSTGRES_PASSWORD: trackrepository
      POSTGRES_DB: trackrepository
    ports:
      - 5432:5432

 # Zookeeper for distributed settings 
  zookeeper:
   image: wurstmeister/zookeeper
   ports:
     - 2181:2181

 # Kafa message bus
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
      - 29999:29999
    links:
      - zookeeper
    depends_on: 
      - zookeeper  
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.200.10.1 # Change this IP address
      KAFKA_CREATE_TOPICS: "trackTopic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 